//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLOGIN2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cours()
        {
            this.fora = new HashSet<forum>();
            this.givens = new HashSet<given>();
            this.grades = new HashSet<grade>();
        }
    
        public int courseID { get; set; }
        public string room { get; set; }
        public string coursecode { get; set; }
        public string coursename { get; set; }
        public int ects { get; set; }
        public string section { get; set; }
        public string prerequisites { get; set; }
        public string day { get; set; }
        public string coursetype { get; set; }
        public int departmentID { get; set; }
        public Nullable<int> semesterno { get; set; }
        public Nullable<int> instructorID { get; set; }
        public Nullable<System.DateTime> examdate { get; set; }
        public Nullable<System.TimeSpan> examtime { get; set; }
        public Nullable<System.TimeSpan> coursestart { get; set; }
        public Nullable<System.TimeSpan> courseend { get; set; }
        public string Quota { get; set; }
    
        public virtual department department { get; set; }
        public virtual instructor instructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<forum> fora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<given> givens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grade> grades { get; set; }
    }
}
