//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLOGIN2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class forum
    {
        public int forumID { get; set; }
        public int courseID { get; set; }
        public string text { get; set; }
        public int studentID { get; set; }
        public string uploadMedia { get; set; }
        public Nullable<System.DateTime> addedtime { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual student student { get; set; }
    }
}
